###---------------------------###
###-------ItzCosmetics--------###
###---------ItzIsonn_---------###
###---------------------------###



papi:
  # Should plugin try to hook into PlaceholderAPI
  enabled: true
  # Output clear text (without formatting) for %cosmetics_used_<type>% placeholder
  clearNameText: false


# The currency that the players will use to pay
# Options: Essentials, PlayerPoints
# For the plugin to work, you must specify one of the suggested options
# To make changes, you need to restart the server
currency: PlayerPoints

# Should plugin remove non-existent cosmetics from the database (works as optimization)
# Caution! If you change the cosmetics id, it will be removed from the database
removeNonExistentCosmetics: false

# The interval in ticks at which sales will be updated (checks for expiration time)
salesUpdateInterval: 200



# Translation
translation:
  # Messages
  messages:
    noPermission: "<red>You don't have permission!"
    unknownCommand: "<red>Unknown command!"
    onlyPlayer: "<red>Only players may execute this command!"
    tooManyArguments: "<red>Too many arguments!"
    notEnoughArguments: "<red>Not enough arguments!"
    reloaded: "<green>Configuration of the ItzCosmetics plugin has been reloaded!"
    unknownArgument: "<red>Unknown argument! Options: %args%"
    unknownPlayer: "<red>Unknown player %player%!"
    unknownType: "<red>Unknown type %type%!"
    unknownRarity: "<red>Unknown rarity %rarity%!"
    unknownCategory: "<red>Unknown category %category%!"
    unknownCosmetics: "<red>Unknown cosmetics with type %type% and id %id%!"
    success: "<green>Successfully changed data for players %players%"
    notSuccess: "<red>Couldn't change the data of any of the players"
    invalidDate: "<red>The sale's expire date is incorrect!"
    saleAlreadyExists: "<red>Sale with this id already exists!"
    percentOnlyNumbers: "<red>The sale's percentage should only use integers!"
    saleDoesNotExist: "<red>Sale with this id doesn't exist!"
    successSale: "<green>Successfully changed the sales' data!"
    saleTemplate: "<#FFB42B>%pos%. <#FFF92B>%id% <white>- <#FFF92B>%expire_date%<white>, <#FFF92B>%percent%%<white>, <#FFF92B>%cosmetics_type_raw%<white>, <#FFF92B>%cosmetics_rarity_raw%<white>, <#FFF92B>%cosmetics_category_raw%<white>, <#FFF92B>%cosmetics_id%"

  # Replacement for the %comment% placeholder (different comment depending on the amount of coins/whether you bought the cosmetics)
  comment:
    notEnoughMoney: "<dark_red>• <red>Not enough money"
    buy: "<dark_green>• <green>Click to buy"
    use: "<dark_green>• <green>Click to use"
    alreadyInUse: "<gold>• <yellow>Already in use"

  # Replacement for the filter placeholder
  status:
    true: "<green>Yes"
    false: "<red>No"

  # Replacement for the %filter_showtype% placeholder
  showType:
    all: "All"
    onlyBought: "Only bought"
    onlyNotBought: "Only not bought"
    onlyEquipped: "Only used"
    onlySale: "Only with sale"

  # Replacement for the %filter_sorttype% placeholder
  sortType:
    type: "By type"
    costInturn: "Cheap ones first"
    costInreverse: "Expensive ones first"

  # Replacement for the %expiry_time% placeholder
  expiryTime:
    overYear: "%years%y. %months%m."
    overMonth: "%months%m. %days%d."
    overDay: "%days%d. %hours%h."
    overHour: "%hours%h. %minutes%min."
    overMinute: "%minutes%min."
    other: "less than a minute"



# Cosmetics' types
types:
  # Id
  walk_effect:
    # Name
    name: "<#7371ec>Walk effect"
    # Cosmetics by default (required)
    default: none
    # Activator
    activator: MOVE:PLAYER
    # Actions
    actions:
      # Default group
      default:
        - "RANDOM:first%50;second%50"
      # Group's id
      first:
        - "ALL*PARTICLE:[world];[x];[y];[z];{particle1};{amount};{offsetX};{offsetY};{offsetZ};{speed}"
      second:
        - "ALL*PARTICLE:[world];[x];[y];[z];{particle2};{amount};{offsetX};{offsetY};{offsetZ};{speed}"

  pin:
    name: "<#7371ec>Pin"
    default: none
    activator: PLACEHOLDER

  kill_effect:
    name: "<#7371ec>Kill effect"
    default: none
    activator: KILL:ALL
    actions:
      default:
        - "ALL*PARTICLE:[opponent_world];[opponent_x];[opponent_y];[opponent_z];{particle};{amount};{offsetX};{offsetY};{offsetZ};{speed}"
        - "ALL*WAIT:5"
        - "ALL*PARTICLE:[opponent_world];[opponent_x]+1;[opponent_y];[opponent_z];{particle};{amount}*5;{offsetX};{offsetY};{offsetZ};{speed}"
        - "ALL*PARTICLE:[opponent_world];[opponent_x]-1;[opponent_y];[opponent_z];{particle};{amount}*5;{offsetX};{offsetY};{offsetZ};{speed}"
        - "ALL*PARTICLE:[opponent_world];[opponent_x];[opponent_y];[opponent_z]+1;{particle};{amount}*5;{offsetX};{offsetY};{offsetZ};{speed}"
        - "ALL*PARTICLE:[opponent_world];[opponent_x];[opponent_y];[opponent_z]-1;{particle};{amount}*5;{offsetX};{offsetY};{offsetZ};{speed}"

  death_sound:
    name: "<#7371ec>Death sound"
    default: none
    activator: DEATH
    actions:
      default:
        - "ALL*SOUND:[player_world];[player_x];[player_y];[player_z];{sound};{volume};{pitch}"



# Cosmetics' rarities
rarities:
  # Id
  default:
    # Cost
    cost: 0
    # Name
    name: "<#C2C2C2>Default"
  common:
    cost: 150
    name: "<#6FF8A8>Common"
  rare:
    cost: 325
    name: "<#5BD3FF>Rare"
  epic:
    cost: 750
    name: "<#E368FF>Epic"
  legendary:
    cost: 1500
    name: "<#F3E060>Legendary"



# Cosmetics' categories
categories:
  # Id
  love:
    # Name
    name: "<#E43A96>Love"
  mystical:
    name: "<#815FE2>Mystical"



# Cosmetics
cosmetics:
  # Type's id
  walk_effect:
    # Cosmetics' id
    none:
      # Name
      name: "<gradient:#37FBCC:#3283FD>None</gradient>"
      # Item used in the menu
      material: STRUCTURE_VOID
      # Rarity
      rarity: DEFAULT
    nature:
      name: "<gradient:#37FBCC:#3283FD>Nature</gradient>"
      material: BLAZE_POWDER
      rarity: EPIC
      # Description (optional)
      description:
        - ""
        - "Feel the nature with this effect,"
        - "fire and water will alternately"
        - "appear under you"
        - ""
      # Data (optional), key:value format
      data:
        particle1: DRIPPING_WATER
        particle2: DRIPPING_LAVA
        amount: 3
        offsetX: 0.1
        offsetY: 0.1
        offsetZ: 0.1
        speed: 0.01

  pin:
    none:
      name: "<gradient:#37FBCC:#3283FD>None</gradient>"
      material: STRUCTURE_VOID
      rarity: DEFAULT
    love:
      name: "<gradient:#37FBCC:#3283FD>Heart</gradient>"
      material: REDSTONE
      rarity: RARE
      categories:
        - LOVE
      description:
        - ""
        - "Show all your love to the world"
        - "using the <3 pin"
        - ""
      data:
        text: "<3"

  kill_effect:
    none:
      name: "<gradient:#37FBCC:#3283FD>None</gradient>"
      material: STRUCTURE_VOID
      rarity: DEFAULT
    flame:
      name: "<gradient:#37FBCC:#3283FD>Flame</gradient>"
      material: BLAZE_ROD
      rarity: LEGENDARY
      categories:
        - MYSTICAL
      description:
        - ""
        - "The enemy's death will be"
        - "illuminated by a spreading flame"
        - ""
      data:
        particle: FLAME
        amount: 2
        offsetX: 0.1
        offsetY: 0.1
        offsetZ: 0.1
        speed: 0.01

  death_sound:
    none:
      name: "<gradient:#37FBCC:#3283FD>None</gradient>"
      material: STRUCTURE_VOID
      rarity: DEFAULT
    explosion:
      name: "<gradient:#37FBCC:#3283FD>Explosion</gradient>"
      material: GUNPOWDER
      rarity: COMMON
      description:
        - ""
        - "The explosion will scare"
        - "the enemy even after your death"
        - ""
      data:
        sound: ENTITY_GENERIC_EXPLODE
        volume: 1
        pitch: 1



# The style of cosmetics' items used in the menu
cosmeticsStyle:
  # The item will glow (as enchanted) if it is used
  glowWhenUse: true

  # Categories' display settings
  categories:
    # Shortening the list
    hide:
      # If there are more categories than the specified amount, all subsequent will be hidden
      amount: 2
      replace: "..."
    # String for cosmetics that have no categories
    empty: "<red>None"
    # Separator between categories
    separator: "<white>, "

  # Item template in the menu
  # The first line is the name, the rest are the description of the item
  template:
    - ""
    - "  » %name%  "
    - ""
    - "  Type: %type%  "
    - "  Rarity: %rarity%  "
    - "  Categories: %categories%  "
    - "  <dark_grey>%description%  "
    - "  Cost: <gold>%cost% coins  "
    - ""
    - "  %comment%  "
    - ""

  # Item template with sale in the menu
  saleTemplate:
    - ""
    - "  » %name%  "
    - ""
    - "  Type: %type%  "
    - "  Rarity: %rarity%  "
    - "  Categories: %categories%  "
    - "  <dark_grey>%description%  "
    - "  Cost: <gold>%sale_cost% coins <gray>(<st>%cost%</st>)  "
    - "  <green>%sale_percent%%</green> sale - <green>%expiry_time%  "
    - ""
    - "  %comment%  "
    - ""

  # Actions when clicking on an item (different depending on the amount of coins/whether you bought cosmetics)
  actions:
    notEnoughMoney:
      - "[name]*SOUND:[world];[x];[y];[z];BLOCK_ANVIL_PLACE;1;1"
      - "[name]*MESSAGE:<red>Not enough money to buy %type% %name%"
    buy:
      - "[name]*SOUND:[world];[x];[y];[z];ENTITY_PLAYER_LEVELUP;1;1"
      - "[name]*MESSAGE:<green>You bought %type% %name%"
    use:
      - "[name]*SOUND:[world];[x];[y];[z];BLOCK_LEVER_CLICK;1;1"
      - "[name]*MESSAGE:<green>You used %type% %name%"
    alreadyInUse:
      - "[name]*SOUND:[world];[x];[y];[z];BLOCK_LAVA_EXTINGUISH;1;1"



# Cosmetics' shop menu
cosmeticsMenu:
  # Title
  title: " » Cosmetics"
  # Size (multiple of 9)
  size: 54
  # Slots where cosmetics items will be placed
  cosmeticsSlots:
    - 11-15
    - 20-24
    - 29-33
    - 38-42
  # Items that will always be visible
  items:
    # Id
    balance:
      # Material
      material: SUNFLOWER
      # Slot(s)
      slots: 0
      # Name
      name: ""
      # Lore
      lore:
        - "  » <gradient:#71bfec:#6b5db3>Balance</gradient>  "
        - ""
        - "  Current balance: <#7371ec>%playerpoints_points%  "
        - ""
    controlPages:
      material: COMPASS
      # Functions (optional), id:clickType format
      functions:
        next_page: LEFT
        prev_page: RIGHT
      slots: 45
      name: ""
      lore:
        - "  » <gradient:#71bfec:#6b5db3>Pages</gradient>  "
        - ""
        - "  Page: <#7371ec>%page_num%<white>/<#7371ec>%page_total%  "
        - ""
    filter:
      material: MAP
      functions:
        menu:filter: ALL
      slots: 53
      name: ""
      lore:
        - "  » <gradient:#71bfec:#6b5db3>Filters</gradient>  "
        - ""
    dec:
      material: BLACK_STAINED_GLASS_PANE
      slots:
        - 8
        - 9
        - 17
        - 18
        - 26
        - 27
        - 35
        - 36
        - 44



# Filter menu
filterMenu:
  title: " » Filters - %page_name%"
  size: 27
  items:
    controlPages:
      material: COMPASS
      functions:
        next_page: LEFT
        prev_page: RIGHT
      slots: 18
      name: ""
      lore:
        - "  » <gradient:#71bfec:#6b5db3>Pages</gradient>  "
        - ""
        - "  Page: <#7371ec>%page_num%<white>/<#7371ec>%page_total%  "
        - ""
    exit:
      material: SPRUCE_DOOR
      functions:
        menu:cosmetics: ALL
      slots: 26
      name: ""
      lore:
        - "  » <gradient:#EF473A:#CB2D3E>Back</gradient>  "
        - ""
    dec:
      material: BLACK_STAINED_GLASS_PANE
      slots:
        - 0
        - 8
        - 9
        - 17
  # Pages
  pages:
    # Page's id
    types:
      # Page's name
      name: "Types"
      # Items displayed only on this page
      items:
        typeWalkEffects:
          material: LEATHER_BOOTS
          functions:
            filter:type:walk_effect:toggle: ALL
          slots: 11
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Walk effects</gradient>  "
            - ""
            - "  Status: %filter_type_walk_effect%  "
            - ""
        typePin:
          material: BOOK
          functions:
            filter:type:pin:toggle: ALL
          slots: 12
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Pin</gradient>  "
            - ""
            - "  Status: %filter_type_pin%  "
            - ""
        typeKillEffect:
          material: IRON_SWORD
          functions:
            filter:type:kill_effect:toggle: ALL
          slots: 13
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Kill effects</gradient>  "
            - ""
            - "  Status: %filter_type_kill_effect%  "
            - ""
        typeDeathSound:
          material: TOTEM_OF_UNDYING
          functions:
            filter:type:death_sound:toggle: ALL
          slots: 14
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Death sound</gradient>  "
            - ""
            - "  Status: %filter_type_death_sound%  "
            - ""
    rarities:
      name: "Rarities"
      items:
        rarityDefault:
          material: CLAY_BALL
          functions:
            filter:rarity:default:toggle: ALL
          slots: 11
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Default rarity</gradient>  "
            - ""
            - "  Status: %filter_rarity_default%  "
            - ""
        rarityCommon:
          material: GLOW_INK_SAC
          functions:
            filter:rarity:common:toggle: ALL
          slots: 12
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Common rarity</gradient>  "
            - ""
            - "  Status: %filter_rarity_common%  "
            - ""
        rarityRare:
          material: SLIME_BALL
          functions:
            filter:rarity:rare:toggle: ALL
          slots: 13
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Rare rarity</gradient>  "
            - ""
            - "  Status: %filter_rarity_rare%  "
            - ""
        rarityEpic:
          material: AMETHYST_SHARD
          functions:
            filter:rarity:epic:toggle: ALL
          slots: 14
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Epic rarity</gradient>  "
            - ""
            - "  Status: %filter_rarity_epic%  "
            - ""
        rarityLegendary:
          material: GOLD_INGOT
          functions:
            filter:rarity:legendary:toggle: ALL
          slots: 15
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Legendary rarity</gradient>  "
            - ""
            - "  Status: %filter_rarity_legendary%  "
            - ""
    categories:
      name: "Categories"
      items:
        categoryWithout:
          material: STRUCTURE_VOID
          functions:
            filter:category:without:toggle: ALL
          slots: 11
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Without category</gradient>  "
            - ""
            - "  Status: %filter_category_without%  "
            - ""
        categoryLove:
          material: ROSE_BUSH
          functions:
            filter:category:love:toggle: ALL
          slots: 12
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Love category</gradient>  "
            - ""
            - "  Status: %filter_category_love%  "
            - ""
        categoryMystical:
          material: ENDER_EYE
          functions:
            filter:category:mystical:toggle: ALL
          slots: 13
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Mystical category</gradient>  "
            - ""
            - "  Status: %filter_category_mystical%  "
            - ""
    extra:
      name: "Extra"
      items:
        showType:
          material: ENDER_PEARL
          functions:
            next_showtype: LEFT
            prev_showtype: RIGHT
          slots: 11
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Show type</gradient>  "
            - ""
            - "  Type: <#7371ec>%filter_showtype%  "
            - ""
        sortType:
          material: BOOK
          functions:
            next_sorttype: LEFT
            prev_sorttype: RIGHT
          slots: 12
          name: ""
          lore:
            - "  » <gradient:#71bfec:#6b5db3>Sort type</gradient>  "
            - ""
            - "  Type: <#7371ec>%filter_sorttype%  "
            - ""



# Purchase confirmation menu
# Placeholders of bought cosmetics are available
confirmMenu:
  # If false, the item will be bought immediately
  enabled: true

  title: " » Purchase confirmation"
  size: 27
  items:
    confirm:
      material: LIME_DYE
      slots: 12
      functions:
        confirm: ALL
        menu:cosmetics: ALL
      name: ""
      lore:
        - "  » <gradient:#62FF80:#00FF3B>Confirm</gradient>  "
        - ""
        - "  Type: %type%  "
        - "  Name: %name%  "
        - "  Cost: <gold>%final_cost% coins  "
        - ""
    cancel:
      material: RED_DYE
      functions:
        menu:cosmetics: ALL
      slots: 14
      name: ""
      lore:
        - "  » <gradient:#EF473A:#CB2D3E>Cancel</gradient>  "
        - ""
    dec:
      material: BLACK_STAINED_GLASS_PANE
      slots:
        - 0
        - 8
        - 9
        - 17
        - 18
        - 26